//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankOfFiji01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank_Interest
    {
        public int Interest_ID { get; set; }
        public System.DateTime Interest_Date { get; set; }
        public decimal Interest_Amount { get; set; }
    }
}
