//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankOfFiji01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Loans
    {
        public int Loan_ID { get; set; }
        public int Cust_ID { get; set; }
        public string Loan_Status { get; set; }
        public string Loan_Amount { get; set; }
        public System.DateTime Loan_Time { get; set; }
        public System.DateTime Loan_ApprovalDate { get; set; }
        public string Loan_Approver { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
