//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankOfFiji01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan_Transaction
    {
        public int LTrans_ID { get; set; }
        public int Cust_ID { get; set; }
        public string LTrans_Description { get; set; }
        public System.DateTime LTrans_Date { get; set; }
        public string LTrans_Adjustment { get; set; }
        public decimal LTrans_Amount { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
