//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankOfFiji01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategory
    {
        public int SubCat_ID { get; set; }
        public string SubCat_Name { get; set; }
        public int Role_ID { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
