//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankOfFiji01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccounts
    {
        public int Cust_ID { get; set; }
        public int Role_ID { get; set; }
        public string User_FName { get; set; }
        public string User_LName { get; set; }
        public string User_Email { get; set; }
        public string UserName { get; set; }
        public string User_Password { get; set; }
        public int UserType_ID { get; set; }
        public int UserAcc_StatusID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Role Role { get; set; }
        public virtual User_Type User_Type { get; set; }
        public virtual UserAccount_Status UserAccount_Status { get; set; }
    }
}
